language: java
 
jdk:
- oraclejdk7
 
env:
# Grails 2.4.3 Not working yet (https://travis-ci.org/yellowsnow/grails-rabbitmq/jobs/34139712)
#- GRAILS_VERSION=2.4.3 UPGRADE="set-grails-version $GRAILS_VERSION"
- GRAILS_VERSION=2.3.11 UPGRADE=upgrade
- GRAILS_VERSION=2.1.5 UPGRADE=upgrade
- GRAILS_VERSION=2.0.4 UPGRADE=upgrade
 
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true
- chmod 775 ./build.sh
 
branches:
only:
- master
 
script: ./build.sh
